### ISSUE TITLE
Create a task list

### ISSUE THREAD

**Issue by sutarmin** [rh1tech/zoia_old#5]
**Situation**: I want to contribute to this project because I think it is valuable. But I don't how what should I start from and how can I be helpful.

**Question**: What do you think about creating a public list of tasks you want to be done in your project?
One task - one github issue.
You might label it with `todo` or something like that, to distinguish it from usual issues. Then one will be able to just pick a task from this list and do a contribution.

**Comment by xtremespb** [comment]
Great idea, thanks! Will do this ;-)
